# https://github.com/canonical/microk8s/issues/1794
# https://jonathangazeley.com/2020/12/30/load-balancing-ingress-with-metallb-on-microk8s/
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
